---
name: "Shopping Application Build" 

on: 
  
  push:
    branches:
      - production
      - testing

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      packer_version: "1.9.4"

    steps:

      - name: "Repository Checkout"
        uses: actions/checkout@v3

      - name: "Packer Installation"
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.packer_version }}

      - name: "Execute packer initilization"
        run: packer init .
        working-directory: ./packer/

      - name: "Packer Validation"
        run: packer validate .
        working-directory: ./packer/

      - name: "Packer Build"
        run: packer build .
        working-directory: ./packer/
